version: "3.7"

services:
  api:
    build:
      context: .
    volumes:
    - ./toy_app:/opt/app
    ports:
    - 8000:8080
    depends_on:
      - toy-mysql
      - redis
    command: "python manage.py runserver 0.0.0.0:8080"

  toy-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
    - mysql-data:/var/lib/mysql-files
    - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
    - 3306:3306

  redis:
    image: redis:latest

volumes:
  mysql-data: