apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "toy.fullname" . }}-ingress
spec:
  defaultBackend:
    service:
      name: {{ include "toy.fullname" . }}
      port:
        number: 80