apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "toy.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
  labels:
    app: {{ include "toy.fullname" . }}
spec:
  rules:
    -http:
      paths:
        - backend:
            serviceName: {{ include "toy.fullname" . }}
            servicePort: 80
          path: /*