apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: toy-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "qtoy.ialab.es"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: toy
spec:
  hosts:
  - "qtoy.ialab.es"
  gateways:
  - toy-gateway
  http:
  - match:
    - uri:
        prefix: /*
    route:
    - destination:
        port:
          number: 8000
        host: qtoy.ialab.es