apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  awsElasticBlockStore:
    volumeID: mysql-volume
    fsType: ext4
    readOnly: false
  storageClassName: ebs-retain
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  selector:
    matchLabels:
      name: mysql-volume
  storageClassName: ebs-retain
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce