apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    for_app: toy-mysql
spec:
  awsElasticBlockStore:
    volumeID: mysql-volume
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: ebs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: ebs-sc
  selector:
    matchLabels:
      for_app: toy-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
