apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
    version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  username: user
  password: password