apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-secrets
  labels:
    app: rabbitmq
    version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  rabbit_user: dXNlcg==
  rabbit_pass: cGFzc3dvcmQ=