### toy-app Service ###
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toy.fullname" . }}
  labels:
    {{- include "toy.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "toy.selectorLabels" . | nindent 4 }}
---
### toy-mysql ###
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "toy.fullname" . }}-mysql*/}}
{{/*  labels:*/}}
{{/*    {{- include "toy.db-labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  ports:*/}}
{{/*    - protocol: TCP*/}}
{{/*      port: 3306*/}}
{{/*      targetPort: 3306*/}}
{{/*  selector:*/}}
{{/*    {{- include "toy.db-labels" . | nindent 4 }}*/}}


