### toy-app Service ###
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toy.fullname" . }}
  labels:
    {{- include "toy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "toy.selectorLabels" . | nindent 4 }}
---
### mysql ###
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toy.fullname" . }}-mysql
  labels:
    {{- include "toy.db-labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    {{- include "toy.db-labels" . | nindent 4 }}
---
### redis
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    version: {{ .Chart.AppVersion | quote }}
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    version: {{ .Chart.AppVersion | quote }}
    app: redis
---
### rabbitmq
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: ClusterIP
  selector:
    version: {{ .Chart.AppVersion | quote }}
    app: redis
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: amqp
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: http


