apiVersion: v1
kind: Service
metadata:
  name: {{ include "toy.fullname" . }}
  labels:
    {{- include "toy.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "toy.selectorLabels" . | nindent 4 }}
