# Generated by Django 3.1.2 on 2020-10-22 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visits',
            field=models.IntegerField(0),
            preserve_default=False,
        ),
    ]
