apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations-job
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/aydevosotros/toy-app:latest
          command: ["/bin/sh", "-c"]
          args: ["python manage.py makemigrations app; python manage.py migrate"]
          volumeMounts:
            - mountPath: "/run/secrets/rabbitmq"
              name: rabbitmq-secrets
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: rabbitmq-secrets
          secret:
            secretName: rabbitmq-secrets
