apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: ghcr.io/aydevosotros/toy-app
          command: ['python', 'manage.py', 'migrate']
      restartPolicy: Never
  backoffLimit: 5